import type { PosLocale } from '../locale/copy';

const copies = {
  uz: {
    title: 'Tizim holati',
    agent: 'Local agent',
    backend: 'Internet',
    fiscal: 'Fiscal',
    marta: 'MARTA',
    printer: 'Printerlar',
    sync: 'Sinxronizatsiya',
    connectionAndSync: 'Server aloqasi',
    online: 'Online',
    offline: 'Offline',
    offlineMode: 'Offline rejim',
    checking: 'Tekshirilmoqda',
    notConfigured: 'Sozlanmagan',
    unknown: 'Noma’lum',
    synchronized: 'Sinxron',
    syncing: 'Sinxronlanmoqda',
    queued: 'navbatda',
    error: 'Xato',
    diagnostics: 'Tizim diagnostikasi',
    diagnosticsHint: 'Batafsil diagnostikani ochish',
    version: 'Agent versiyasi',
    lastSuccess: 'Oxirgi muvaffaqiyatli sync',
    lastAttempt: 'Oxirgi urinish',
    pending: 'Navbatdagi amallar',
    failed: 'Xato amallar',
    noData: 'Ma’lumot yo‘q',
    refresh: 'Qayta tekshirish',
    copy: 'Nusxalash',
    copied: 'Nusxalandi',
    close: 'Yopish',
    failures: 'Sync xatolari',
  },
  'uz-crl': {
    title: 'Тизим ҳолати',
    agent: 'Local agent',
    backend: 'Интернет',
    fiscal: 'Fiscal',
    marta: 'MARTA',
    printer: 'Принтерлар',
    sync: 'Синхронизация',
    connectionAndSync: 'Сервер алоқаси',
    online: 'Online',
    offline: 'Offline',
    offlineMode: 'Offline режим',
    checking: 'Текширилмоқда',
    notConfigured: 'Созланмаган',
    unknown: 'Номаълум',
    synchronized: 'Синхрон',
    syncing: 'Синхронланмоқда',
    queued: 'навбатда',
    error: 'Хато',
    diagnostics: 'Тизим диагностикаси',
    diagnosticsHint: 'Батафсил диагностикани очиш',
    version: 'Agent версияси',
    lastSuccess: 'Охирги муваффақиятли sync',
    lastAttempt: 'Охирги уриниш',
    pending: 'Навбатдаги амаллар',
    failed: 'Хато амаллар',
    noData: 'Маълумот йўқ',
    refresh: 'Қайта текшириш',
    copy: 'Нусхалаш',
    copied: 'Нусхаланди',
    close: 'Ёпиш',
    failures: 'Sync хатолари',
  },
  ru: {
    title: 'Состояние системы',
    agent: 'Local agent',
    backend: 'Интернет',
    fiscal: 'Fiscal',
    marta: 'MARTA',
    printer: 'Принтеры',
    sync: 'Синхронизация',
    connectionAndSync: 'Связь с сервером',
    online: 'Online',
    offline: 'Offline',
    offlineMode: 'Офлайн-режим',
    checking: 'Проверка',
    notConfigured: 'Не настроено',
    unknown: 'Неизвестно',
    synchronized: 'Синхронно',
    syncing: 'Синхронизация',
    queued: 'в очереди',
    error: 'Ошибка',
    diagnostics: 'Диагностика системы',
    diagnosticsHint: 'Открыть подробную диагностику',
    version: 'Версия агента',
    lastSuccess: 'Последняя успешная синхронизация',
    lastAttempt: 'Последняя попытка',
    pending: 'В очереди',
    failed: 'Ошибок',
    noData: 'Нет данных',
    refresh: 'Проверить снова',
    copy: 'Копировать',
    copied: 'Скопировано',
    close: 'Закрыть',
    failures: 'Ошибки синхронизации',
  },
} as const;

export function getSystemHealthCopy(locale: PosLocale) {
  return copies[locale] ?? copies.uz;
}
