// Generated by backend/scripts/generate_sale_units.py. Do not edit.
export const SALE_UNITS = {
  piece: {
    enum: 'PIECE',
    name: 'Piece',
    step: 1,
    precision: 0,
    quantityInput: false,
    allowZero: false,
    markingAllowed: true,
    labels: {
      uz: 'dona',
      'uz-crl': 'дона',
      'uz-Cyrl': 'дона',
      ru: 'шт',
    },
    adminLabelKey: 'fields.saleUnitPiece',
    adminPriceKey: 'fields.pricePerPiece',
    quantityKey: 'common:quantityUnits.piece',
    posPriceKey: 'pricePerPiece',
    posTitleKey: 'pieceQuantityTitle',
    posInvalidKey: 'pieceQuantityInvalid',
  },
  kg: {
    enum: 'KILOGRAM',
    name: 'Kilogram',
    step: 0.001,
    precision: 3,
    quantityInput: true,
    allowZero: false,
    markingAllowed: false,
    labels: {
      uz: 'kg',
      'uz-crl': 'кг',
      'uz-Cyrl': 'кг',
      ru: 'кг',
    },
    adminLabelKey: 'fields.saleUnitKilogram',
    adminPriceKey: 'fields.pricePerKilogram',
    quantityKey: 'common:quantityUnits.kilogram',
    posPriceKey: 'pricePerKilogram',
    posTitleKey: 'weightTitle',
    posInvalidKey: 'weightInvalid',
  },
  pors: {
    enum: 'PORTION',
    name: 'Portion',
    step: 0.5,
    precision: 1,
    quantityInput: true,
    allowZero: true,
    markingAllowed: false,
    labels: {
      uz: 'pors',
      'uz-crl': 'pors',
      'uz-Cyrl': 'pors',
      ru: 'pors',
    },
    adminLabelKey: 'fields.saleUnitPortion',
    adminPriceKey: 'fields.pricePerPortion',
    quantityKey: 'common:quantityUnits.portion',
    posPriceKey: 'pricePerPortion',
    posTitleKey: 'portionTitle',
    posInvalidKey: 'portionInvalid',
  },
} as const;

export type SaleUnit = keyof typeof SALE_UNITS;
export const SALE_UNIT_IDS = Object.keys(SALE_UNITS) as [SaleUnit, ...SaleUnit[]];
export const DEFAULT_SALE_UNIT: SaleUnit = 'piece';
export function getSaleUnit(unit?: string | null) {
  if (unit === undefined || unit === null || unit === '') return SALE_UNITS[DEFAULT_SALE_UNIT];
  if (!Object.prototype.hasOwnProperty.call(SALE_UNITS, unit)) throw new Error(`Unknown sale unit: ${unit}`);
  return SALE_UNITS[unit as SaleUnit];
}
export function saleUnitLabel(unit?: string | null, locale = 'uz') {
  const labels = getSaleUnit(unit).labels;
  return labels[locale as keyof typeof labels] ?? labels.uz;
}
export function isValidSaleQuantity(value: number, unit?: string | null, allowZero = false) {
  const rule = getSaleUnit(unit);
  const scaled = value * 1000;
  return (
    Number.isFinite(value) &&
    value >= (allowZero ? 0 : rule.step) &&
    value <= 999_999_999.999 &&
    Math.abs(scaled - Math.round(scaled)) < 0.0000001 &&
    Math.round(scaled) % Math.round(rule.step * 1000) === 0
  );
}
